# Generated by Django 4.2.9 on 2024-01-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=60)),
                ('synopsis', models.TextField()),
                ('release_year', models.DateField()),
                ('duration', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('AC', 'Ação'), ('AV', 'Aventura'), ('RO', 'Romance'), ('TE', 'Terror'), ('DR', 'Drama'), ('SU', 'Suspense'), ('FC', 'Ficção Cientifíca'), ('CO', 'Comédia'), ('DO', 'Documentário'), ('AN', 'Animação'), ('NI', 'Não informado')], default='NI', max_length=2)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='capas')),
            ],
        ),
    ]
