# Generated by Django 5.0.1 on 2024-01-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=100)),
                ('year_publication', models.IntegerField()),
                ('number_pages', models.IntegerField()),
                ('name_author', models.CharField(max_length=100)),
                ('name_editora', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
