# Generated by Django 5.0.1 on 2024-01-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='name_author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='name_book',
            new_name='book_name',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='name_editora',
            new_name='publishing_company',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='year_publication',
            new_name='year_of_publication',
        ),
    ]
