# Generated by Django 4.2.9 on 2024-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('local', models.TextField()),
                ('participant_name', models.CharField(max_length=60)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
