# Generated by Django 4.2.9 on 2024-01-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reunioes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
