# Generated by Django 5.0.1 on 2024-01-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=350)),
                ('category', models.CharField(max_length=60)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
